version: "3"
services:
  nginx:
   
    ports:
      - "8080:80"
      
  veezo:
    build:
      context: .
      args:
        NODE_ENV: production
  
    environment:
      - NODE_ENV=production
      - FILE_PORT=4000
      - AZURE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=nichlabs;AccountKey=3cXxsexFewMsiuTkm5yW5zd5NsQXhNhQIgiU52kOehimwIyA1AzQxZSrrVoTghQkLl7nG3DaJNrF+AStWoHSYQ==;EndpointSuffix=core.windows.net
      - MONGO_USERNAME=amschel
      - MONGO_PASSWORD=@iamLehcsma9
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=files
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amschel
      - MONGO_INITDB_ROOT_PASSWORD=@iamLehcsma9
