version: "3"
services:
  nginx:
    ports:
      - "8000:80"
  veezo:
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - ./:/app
     # - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amschel
      - MONGO_INITDB_ROOT_PASSWORD=iamLehcsma9