version: "3"
services:
  veezo:
    build: .
    ports:
     - "8000:4000" #the first port is for our host machine/server, the second port is docker's port where our app is listening
    environment:
      - PORT=4000 # this is the port our node app will be listening to in the docker container, so if we direct traffic here, our node app will be accessed
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.18
   
    volumes:
      - mongo-db:/data/db #here we are saying we want to persist this data. the path is where data is stored

volumes:
  mongo-db:

  