version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - veezo
     
  veezo:
    build: .
    image: docker.io/tefrotech/veezo:v1
    
    environment:
      - PORT=4000 # this is the port our node app will be listening to in the docker container, so if we direct traffic here, our node app will be accessed
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.18
   
    volumes:
      - mongo-db:/data/db #here we are saying we want to persist this data. the path is where data is stored

volumes:
  mongo-db:

  