

export const config={
MONGO_USERNAME:process.env.MONGO_USERNAME,
MONGO_PASSWORD:process.env.MONGO_PASSWORD,
MONGO_IP:process.env.MONGO_IP || 'mongo',
MONGO_PORT:process.env.MONGO_PORT || 27017,
MONGO_DATABASE:process.env.MONGO_DATABASE,
AZURE_CONNECTION_STRING:process.env.AZURE_CONNECTION_STRING,
PORT:process.env.PORT || 4000,
AZURE_CLIENT_ID:process.env.AZURE_CLIENT_ID,
AZURE_CLIENT_SECRET:process.env.AZURE_CLIENT_SECRET,
AZURE_TENANT_ID:process.env.AZURE_TENANT_ID,
AZURE_SUBSCRIPTION_ID:process.env.AZURE_SUBSCRIPTION_ID,
AZURE_RESOURCE_GROUP:process.env.AZURE_RESOURCE_GROUP,
AZURE_ACCOUNT_NAME :process.env.AZURE_ACCOUNT_NAME 

}
